### ISSUE TITLE
Compile cuda kernels for RoPE Fail

### ISSUE THREAD

**Issue by Youngkwan-Cho** [naver/croco#7]
Hello, 
I have problem compiling cuda kernels for RoPE. This seem to be some kind of compatibility issue with ninja, PyTorch, cuda and etc. Can you specify your chosen version of ninja-build, cuda, torch, python extensions while running Crocov2? Also, how much gpu memory is required to run Crocov2? Thank you.

> (croco) youngkwan@deep16:~/croco/models/curope$ python setup.py build_ext --inplace
running build_ext
building 'curope' extension
Emitting ninja build file /home/youngkwan/croco/models/curope/build/temp.linux-x86_64-cpython-37/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda/bin/nvcc -I/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/include -I/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/include/TH -I/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/youngkwan/anaconda3/envs/croco/include/python3.7m -c -c /home/youngkwan/croco/models/curope/kernels.cu -o /home/youngkwan/croco/models/curope/build/temp.linux-x86_64-cpython-37/kernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --ptxas-options=-v --use_fast_math -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_37,code=compute_37 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=curope -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /home/youngkwan/croco/models/curope/build/temp.linux-x86_64-cpython-37/kernels.o
/usr/local/cuda/bin/nvcc -I/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/include -I/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/include/TH -I/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/youngkwan/anaconda3/envs/croco/include/python3.7m -c -c /home/youngkwan/croco/models/curope/kernels.cu -o /home/youngkwan/croco/models/curope/build/temp.linux-x86_64-cpython-37/kernels.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 --ptxas-options=-v --use_fast_math -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_37,code=compute_37 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=curope -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/local/cuda/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 9 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 9 are not supported!
      |  ^~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1522, in _run_ninja_build
    env=env)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    'build_ext': BuildExtension
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
    build_ext.build_extensions(self)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1238, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/youngkwan/anaconda3/envs/croco/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1538, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by PhilippeWeinzaepfel** [comment]
It looks like you are using gcc 9 but a cuda that is not compatible with it (so probably <11), can you try downgrading gcc < 9  or upgrading to cuda >= 11 ?

**Comment by Youngkwan-Cho** [comment]
Thank you for your reply.
I have downgraded gcc version but still having problem executing ninja build.
I am getting new error codes and after searching it, I found out that this can happen if ninja, PyTorch, cuda and python versions does not work each other.
Thus, are you able to tell me the version of those 4 extensions you applied while running?

**Comment by PhilippeWeinzaepfel** [comment]
We did not use ninja but conda in our case. Here are the versions of python, gcc, cuda, pytorch that we used (but we also tried with some other versions without problems)
* python 3.9
* gcc 7.3.1
* cuda 11.3
* pytorch 1.11.0

**Comment by Youngkwan-Cho** [comment]
Thank you so much. I will try it
